"""
PANOPTICON -- beach: the bay's fish paths. Loose closed loops under the surface, fitted to the sculpt's own bed
(beach_build.ground_z) and kept off the shore, the yacht and the coral heads; written as GDScript consts to
maps/beach/fish/beach_fish_paths.gd, which beach_fish.gd swims.

    python3 tools/modelling/maps/beach/beach_fish_paths.py
"""

import math
import os
import sys

_HOME = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HOME)
import beach_build as B  # noqa: E402
from beach_lib import Rng, bearing_of  # noqa: E402

OUT = os.path.join(_HOME, "..", "..", "..", "..", "maps", "beach", "fish", "beach_fish_paths.gd")
SPECIES = ("yellow_tang", "clownfish", "blue_tang", "angelfish", "parrotfish")
# (species, fish, zone, length m): schools of tangs, clownfish pairs over the coral, single angels and parrots
SCHOOLS = (
    (0, 5, "shallow", 0.65), (0, 6, "mid", 0.65), (0, 5, "mid", 0.65),
    (2, 4, "mid", 0.75), (2, 4, "shallow", 0.75),
    (1, 2, "reef", 0.5), (1, 2, "reef", 0.5),
    (3, 1, "mid", 0.9), (3, 1, "shallow", 0.9), (3, 1, "mid", 0.9),
    (4, 1, "mid", 1.0), (4, 1, "shallow", 1.0), (4, 1, "mid", 1.0),
)
POINTS = 32
YACHT_CLEAR = (13.0, 4.0)    # metres round the yacht kept clear, unless deeper than this


def depth_at(x, y):
    return B.WATER_Z - B.ground_z(bearing_of((x, y, 0.0)), math.hypot(x, y))


def reef_heads():
    heads = []
    real = B.boulder

    def spy(m, cx, cy, size, seed, **kw):
        if kw.get("zone") == "reef":
            heads.append((cx, cy, size, kw["gz"] + 0.35 * size))
        return real(m, cx, cy, size, seed, **kw)

    B.boulder = spy
    B.build_rocks()
    B.boulder = real
    return heads


def ok(x, y, fy, zone, heads):
    b, r = bearing_of((x, y, 0.0)), math.hypot(x, y)
    if r > B.wl(b) - 1.5 or x > 38.0 or r > 60.0:
        return False                                      # inside the bay, short of the jetty tips
    d = depth_at(x, y)
    fd = B.WATER_Z - fy
    if d < fd + (0.3 if zone != "mid" else 0.7):
        return False                                      # never at the bed or the shore
    if zone == "shallow" and d > 1.45:
        return False
    if r < YACHT_CLEAR[0] and fd < YACHT_CLEAR[1]:
        return False
    for hx, hy, s, top in heads:
        if math.hypot(x - hx, y - hy) < s + 0.8 and fy < top + 0.35:
            return False
    return True


def loop(rr, zone, heads, centre=None):
    for _ in range(20000):
        if centre:
            cx, cy = centre[0] + rr.u(-1.0, 1.0), centre[1] + rr.u(-1.0, 1.0)
            a, c = rr.u(1.8, 3.2), rr.u(1.4, 2.4)
        else:
            b = rr.u(0.0, 360.0)
            r = rr.u(10.0, 60.0)
            cx, cy = r * math.cos(math.radians(-b)), r * math.sin(math.radians(-b))
            a, c = (rr.u(5.0, 13.0), rr.u(3.0, 7.0)) if zone == "mid" else (rr.u(6.0, 14.0), rr.u(1.6, 3.0))
        if zone == "shallow":                             # long and thin, along the shore
            rot = math.atan2(cy, cx) + math.pi / 2.0
        else:
            rot = rr.u(0.0, math.pi)
        fd = {"shallow": rr.u(0.32, 0.5), "mid": rr.u(0.8, 1.9), "reef": max(0.6, centre[2] - rr.u(0.6, 1.0)) if centre else 0.0}[zone]
        fy = B.WATER_Z - fd
        h1, h2, p1, p2 = rr.u(0.0, 0.15), rr.u(0.0, 0.08), rr.u(0.0, 6.3), rr.u(0.0, 6.3)
        pts = []
        for k in range(POINTS):
            t = k / POINTS * 2.0 * math.pi
            w = 1.0 + h1 * math.sin(2.0 * t + p1) + h2 * math.sin(3.0 * t + p2)
            lx, ly = a * math.cos(t) * w, c * math.sin(t) * w
            x = cx + lx * math.cos(rot) - ly * math.sin(rot)
            y = cy + lx * math.sin(rot) + ly * math.cos(rot)
            yy = fy + 0.12 * math.sin(2.0 * t + p2)
            if not ok(x, y, yy, zone, heads):
                break
            pts.append((x, yy, -y))                       # Blender -> Godot
        else:
            return pts
    raise SystemExit("no room for a %s loop" % zone)


def main():
    rr = Rng(B.SEED + 900)
    heads = reef_heads()
    patches = []                                          # coral patch centres: the biggest heads
    for hx, hy, s, top in sorted(heads, key=lambda h: -h[2]):
        if math.hypot(hx, hy) > YACHT_CLEAR[0] + 3.0 and B.WATER_Z - top < 3.6 and all(math.hypot(hx - p[0], hy - p[1]) > 8.0 for p in patches):
            patches.append((hx, hy, B.WATER_Z - top))
    lines = ["# GENERATED by tools/modelling/maps/beach/beach_fish_paths.py: do not edit.",
             "# Each school: species row in beach_fish_albedo, fish count, length (m), its closed loop (world x, y, z, ...).",
             "extends RefCounted", "", "const SCHOOLS := ["]
    used = 0
    for sp, n, zone, length in SCHOOLS:
        centre = None
        if zone == "reef":
            centre = patches[used % len(patches)]
            used += 1
        pts = loop(rr, zone, heads, centre)
        body = ", ".join("%.2f, %.2f, %.2f" % p for p in pts)
        lines.append("\t[%d, %d, %.2f, [%s]],   # %s, %s" % (sp, n, length, body, SPECIES[sp], zone))
    lines.append("]")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("fish: %d schools, %d fish, %d coral heads avoided -> %s" % (
        len(SCHOOLS), sum(s[1] for s in SCHOOLS), len(heads), os.path.relpath(OUT)))


if __name__ == "__main__":
    main()
