class_name PanopticonEye
extends Node3D

## The eye over the yard: a red ball with a black band round it that no prisoner
## can read anything from.
##
## [b]It is two primitives, and that is on purpose[/b]
##
## There was a thirty-one-metre tower here -- socket, lids, brow, crown -- until
## 2026-09-10. It was removed because it was architecture nobody asked for, and
## because the arena is a greybox with no art in it yet. What is left is the eye
## itself, floating over the centre of the ring with nothing holding it up. Git
## has the tower if it is ever wanted back.
##
## [b]The one thing this class must never do[/b]
##
## Ryan settled guard vision on 2026-09-09 (pod fact
## [code]panopticon.open.guard_vision[/code]): the guard can see the whole ring
## at once -- no part of the course is hidden from the tower by geometry -- but
## the guard's point of view is NOT 360 degrees. They see what they are looking
## at, with an ordinary field of view. Attention is therefore a real, scarce
## resource the guard spends, and the entire tension of the game is that the
## prisoners cannot tell where it is being spent.
##
## So the eye [b]must not carry a single bit of information about the guard[/b].
## It does not turn towards them, brighten towards them, track them, or change
## when they aim, fire, reload, zoom, or leave the tower entirely. There is no
## reference in this file to a camera, to [MatchController], to the rifle or to
## the seat, and adding one would not be a feature -- it would delete the
## mechanic the game is named after.
##
## That is a promise, so it is kept structurally rather than by discipline:
##
## 1. [b]The form is a solid of revolution.[/b] Both meshes are generated by
##    revolution about the tower's own vertical axis, sit on that axis, and carry
##    no rotation. A shape with no distinguishable side cannot point at anything,
##    whatever anybody later writes in [method _process]. The pupil is a full
##    360-degree band, so every prisoner on the ring sees the eye looking dead at
##    them, all the time, from every position -- which is the panopticon exactly.
## 2. [b]The only animation is the wall clock.[/b] [member EyeProfile.pulse_hz]
##    breathes the glow on a timer that knows nothing. Nothing else moves.
## 3. [code]tests/test_tower.gd[/code] asserts both of the above, so a later
##    change that breaks them fails the suite rather than shipping.
##
## [b]What the strip-back gave up[/b]
##
## The old socket was a 15 m wall at r=8.5 that enclosed the guard, and it is
## what made the tower a literal one-way mirror: opaque from the ring, culled
## away from inside. Without it the guard stands on an open platform in plain
## sight of the course, which is where the arena was before the tower was built.
## The eye still cannot be seen through and still cannot be read for a bearing,
## but it no longer hides the guard's body. Whether it should is a design ruling,
## not something to restore quietly.
##
## [b]It is not in the guard's way[/b]
##
## Nothing here exists below y=12.7, and a guard's camera tops out at y=3.0 with
## the jump apex included. The eye's lowest rim is therefore 48 degrees above the
## horizon from anywhere the guard can stand, and the ring is at or below the
## horizon, so no surface of the eye is ever between them and it.
##
## That is checked on a screen rather than assumed. Across 31 renders from the
## guard's eye -- all four bearings, pitch -35 to +40 degrees, the very edge of
## the platform and the top of a jump -- the eye stands in front of 0 pixels of
## arena geometry, measured against a mask of the arena rather than by eye. The
## eye enters frame at all only above +37 degrees of elevation on the axis, or
## +11 at the platform edge, and when it does it is silhouetted against sky.
##
## Its shadow is the one thing it does put on the ground, and it lands at r=25.1
## at the furthest, on the pit floor 12 m down. An overhead render puts none of
## it on the r=35 running deck.
##
## Nothing here has collision and nothing here is on the rifle's hit mask, so the
## guard shoots straight through the eye and it costs the physics server nothing.
##
## [b]Scenery, not a mechanic[/b]
##
## As of today the eye does nothing at all. It has no state, no signals and no
## gameplay. It is presence. Ideas for what it might do belong in the pod as open
## questions for Ryan, not in this file.
##
## [b]Renderer[/b]
##
## GL Compatibility, which is pinned for this project. Albedo, metallic,
## roughness, emission and backface culling are the whole surface model, and the
## form is primitive meshes. There is no custom shader to fail to compile.

## Materials the profile is written onto. They are exported rather than found by
## walking the mesh children so that this script never has to guess which surface
## is which: the scene says it, once, in one place.
##
## They are [member Resource.resource_local_to_scene], so each eye owns the
## materials it draws with and writing a profile onto one eye cannot reach
## another -- or, more to the point, cannot leak out of a test and into the rest
## of the suite. [code]tests/test_tower.gd[/code] asserts that the material this
## script writes to is the same object the mesh renders with, because a
## mis-remapped local resource fails silently: the profile is applied perfectly,
## to a copy nothing draws.
@export var iris_material: StandardMaterial3D
@export var pupil_material: StandardMaterial3D

## Look and size. Falls back to a default-constructed [EyeProfile] with a warning
## rather than to nothing, because an eye that silently failed to appear is a bug
## that reads as "the tower is just a platform again".
@export var profile: EyeProfile

## Emission energy the pulse swings around, taken from the profile at ready so
## that [method _process] never touches the resource.
var _glow_energy: float = 0.0

## Seconds since this node entered the tree. Its own clock rather than
## [method Time.get_ticks_msec] so that the pulse is unaffected by how long the
## menu was open, and so a headless run with no display never accumulates one.
var _pulse_time: float = 0.0


func _ready() -> void:
	if profile == null:
		push_warning("PanopticonEye has no EyeProfile; falling back to defaults.")
		profile = EyeProfile.new()

	scale = Vector3.ONE * profile.size_scale

	_apply_iris()
	_apply_pupil()

	_glow_energy = profile.iris_glow_energy
	set_process(_pulses())


func _process(delta: float) -> void:
	_pulse_time += delta
	iris_material.emission_energy_multiplier = glow_energy_at(_pulse_time)


## The glow [param seconds] into the breath.
##
## A pure function of the clock and the profile, which is the whole argument for
## letting the eye move at all: it takes no guard, no camera and no match state,
## so there is no value anybody could pass it that would make it say something.
## It is public so the suite can assert the shape of the breath without racing
## the render clock -- see [code]tests/test_tower.gd[/code].
##
## The breath dips rather than swings, so that
## [member EyeProfile.iris_glow_energy] is the brightest the eye ever gets and
## the value in the inspector is the value on the screen. It also means the first
## frame drawn matches the frame [method _ready] set up, with no pop.
func glow_energy_at(seconds: float) -> float:
	var dip: float = 0.5 - 0.5 * cos(TAU * profile.pulse_hz * seconds)
	return _glow_energy * (1.0 - profile.pulse_depth * dip)


## Whether the glow moves at all. Both knobs have to be non-zero, so either one
## alone is enough to nail the eye perfectly still.
func _pulses() -> bool:
	return iris_material != null and profile.pulse_hz > 0.0 and profile.pulse_depth > 0.0


func _apply_iris() -> void:
	if not _usable(iris_material, "iris_material"):
		return
	iris_material.albedo_color = profile.iris_color
	iris_material.metallic = profile.iris_metallic
	iris_material.roughness = profile.iris_roughness
	iris_material.emission_enabled = profile.iris_glow_energy > 0.0
	iris_material.emission = profile.iris_glow
	iris_material.emission_energy_multiplier = profile.iris_glow_energy


func _apply_pupil() -> void:
	if not _usable(pupil_material, "pupil_material"):
		return
	pupil_material.albedo_color = profile.pupil_color
	pupil_material.metallic = profile.pupil_metallic
	pupil_material.roughness = profile.pupil_roughness


## Reports a missing material, and refuses to let a front-face-culled or
## depth-testless one through quietly.
##
## Either of those turns the eye inside out. With culling off or reversed the
## inside of the ball draws as well as the outside, and with depth testing off it
## draws over the whole ring from anywhere on the map. Both are one line to get
## wrong in the inspector and neither can be seen in a headless run, so they are
## checked here as well as in the suite.
func _usable(material: StandardMaterial3D, field: String) -> bool:
	if material == null:
		push_error("PanopticonEye.%s is unset; the eye will render untextured." % field)
		return false
	if material.cull_mode != BaseMaterial3D.CULL_BACK:
		push_error("PanopticonEye.%s must be backface-culled." % field)
	if material.no_depth_test:
		push_error("PanopticonEye.%s has depth testing off; it would draw over the whole ring." % field)
	return true
