#!/usr/bin/env python3
"""Rewrites docs/TEXTURES.md below its marker: every shipped .glb material, its texture, sheet slice and recolour.
Exits 1 when a live texture is missing or is in no sheet (the three standalone PNGs excepted)."""

import os
import posixpath
import struct
import subprocess
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "modelling", "lib"))
import glb_textures  # noqa: E402

DOC = "docs/TEXTURES.md"
MARKER = "<!-- generated by tools/textures/audit.py: do not edit below -->"
STANDALONE = ("lava_albedo.png", "map_base_lava_emissive.png", "forest_mist_albedo.png")
COMPONENT = {5126: ("f", 4, 1.0), 5123: ("H", 2, 65535.0), 5121: ("B", 1, 255.0)}


def git_files(pattern):
    out = subprocess.check_output(["git", "-C", ROOT, "ls-files", pattern]).decode()
    return sorted(out.split())


def slices(path):
    """Slice names in an .ase file (chunk 0x2022)."""
    with open(path, "rb") as fh:
        data = fh.read()
    names, pos = [], 128
    for _frame in range(struct.unpack("<H", data[6:8])[0]):
        size, _magic, old, _dur, _pad, new = struct.unpack("<IHHHHI", data[pos:pos + 16])
        chunk = pos + 16
        for _c in range(new or old):
            csize, ctype = struct.unpack("<IH", data[chunk:chunk + 6])
            if ctype == 0x2022:
                n = struct.unpack("<H", data[chunk + 18:chunk + 20])[0]
                names.append(data[chunk + 20:chunk + 20 + n].decode("utf-8"))
            chunk += csize
        pos += size
    return names


def vertex_colours(js, binary):
    """{material index: [(share %, (r, g, b))]} for materials whose COLOR_0 is not all white."""
    seen = {}
    for mesh in js.get("meshes", []):
        for prim in mesh["primitives"]:
            acc_i = prim["attributes"].get("COLOR_0")
            if acc_i is None or "material" not in prim:
                continue
            acc = js["accessors"][acc_i]
            view = js["bufferViews"][acc["bufferView"]]
            code, width, top = COMPONENT[acc["componentType"]]
            comps = 3 if acc["type"] == "VEC3" else 4
            stride = view.get("byteStride") or width * comps
            start = view.get("byteOffset", 0) + acc.get("byteOffset", 0)
            tally = seen.setdefault(prim["material"], {})
            for i in range(acc["count"]):
                rgb = struct.unpack_from("<3" + code, binary, start + i * stride)
                key = tuple(round(v / top, 2) for v in rgb)
                tally[key] = tally.get(key, 0) + 1
    out = {}
    for mat, tally in seen.items():
        total = sum(tally.values())
        if tally.get((1.0, 1.0, 1.0), 0) == total:
            continue
        ranked = sorted(tally.items(), key=lambda kv: -kv[1])
        out[mat] = (len(tally), [(100.0 * n / total, rgb) for rgb, n in ranked[:4]])
    return out


def rgb(values):
    return "(%s)" % ", ".join("%.3g" % v for v in values[:3])


def main():
    sheet_of = {}                                   # textures/<png> repo path -> sheet file name
    for sheet in git_files("*/textures/*.ase"):
        if sheet.endswith(("_photo.ase", "_hand.ase")):   # alternate sheets (use_sheet.sh), never exported
            continue
        for name in slices(os.path.join(ROOT, sheet)):
            sheet_of[posixpath.join(posixpath.dirname(sheet), name + ".png")] = posixpath.basename(sheet)

    rows, factor, vertex, flat, live, missing = [], {}, [], [], set(), []
    for glb in git_files("*.glb"):
        js, binary = glb_textures.read(os.path.join(ROOT, glb))
        images, textures = js.get("images", []), js.get("textures", [])
        vcol = vertex_colours(js, binary)

        def path_of(ref):
            if ref is None:
                return None
            uri = images[textures[ref["index"]]["source"]]["uri"]
            return posixpath.normpath(posixpath.join(posixpath.dirname(glb), uri))

        for i, mat in enumerate(js.get("materials", [])):
            pbr = mat.get("pbrMetallicRoughness", {})
            albedo, glow = path_of(pbr.get("baseColorTexture")), path_of(mat.get("emissiveTexture"))
            mult = pbr.get("baseColorFactor", [1.0, 1.0, 1.0, 1.0])
            tinted = [round(v, 4) for v in mult[:3]] != [1.0, 1.0, 1.0]
            for tex in (albedo, glow):
                if tex is None:
                    continue
                live.add(tex)
                if not os.path.exists(os.path.join(ROOT, tex)):
                    missing.append("%s: %s names %s, which does not exist" % (glb, mat["name"], tex))
            rows.append((glb, mat["name"], albedo, mult if tinted else None, glow))
            if albedo is None:
                flat.append((glb, mat["name"], mult))
            elif tinted:
                factor.setdefault((albedo, tuple(round(v, 4) for v in mult[:3])), []).append(
                    "%s: %s" % (posixpath.basename(glb), mat["name"]))
            if i in vcol and albedo is not None:
                vertex.append((glb, mat["name"], albedo, vcol[i]))

    for scene in git_files("*.tscn") + git_files("*.tres"):
        with open(os.path.join(ROOT, scene), encoding="utf-8") as fh:
            for line in fh:
                if 'type="Texture2D"' in line and "/textures/" in line:
                    live.add(line.split('path="res://')[1].split('"')[0])

    def where(tex):
        if tex is None:
            return "-"
        if tex in sheet_of:
            return "%s / %s" % (sheet_of[tex], posixpath.basename(tex)[:-4])
        return "standalone PNG" if posixpath.basename(tex) in STANDALONE else "NOT IN A SHEET"

    for tex in sorted(live):
        if tex not in sheet_of and posixpath.basename(tex) not in STANDALONE:
            missing.append("%s is live but is no slice of a sheet" % tex)
    drawn = set(git_files("*/textures/*.png"))
    unused = sorted(drawn - live)

    out = [MARKER, "", "## Recolours: one texture, a colour multiplier in the material", "",
           "The game multiplies the texture by this colour (linear RGB). The recoloured look is not a file.", "",
           "| Texture | Multiplier | Materials |", "|---|---|---|"]
    for (tex, mult), users in sorted(factor.items()):
        out.append("| %s | %s | %s |" % (tex, rgb(mult), "; ".join(users)))
    out += ["", "## Recolours: one texture, a colour painted per vertex (COLOR_0)", "",
            "Up to four commonest colours and the share of vertices wearing each; many colours means shading.", "",
            "| Model | Material | Texture | Vertex colours |", "|---|---|---|---|"]
    for glb, name, tex, (count, ranked) in vertex:
        shown = ", ".join("%s %d%%" % (rgb(c), share) for share, c in ranked)
        out.append("| %s | %s | %s | %d: %s |" % (glb, name, posixpath.basename(tex), count, shown))
    out += ["", "## Flat colours: materials with no texture", "",
            "| Model | Material | Colour (linear RGB) |", "|---|---|---|"]
    for glb, name, mult in flat:
        out.append("| %s | %s | %s |" % (glb, name, rgb(mult)))
    out += ["", "## Every material in every shipped model", "",
            "| Model | Material | Texture | Sheet / slice | Multiplier | Glow texture |", "|---|---|---|---|---|---|"]
    for glb, name, albedo, mult, glow in rows:
        out.append("| %s | %s | %s | %s | %s | %s |" % (
            glb, name, albedo or "none", where(albedo), rgb(mult) if mult else "-",
            posixpath.basename(glow) if glow else "-"))
    textured = [r for r in rows if r[2] is not None]
    out += ["", "## Check", "",
            "- Materials: %d in %d models; %d textured, %d flat colour." % (
                len(rows), len(set(r[0] for r in rows)), len(textured), len(flat)),
            "- Textured materials with a multiplier other than white: %d (%d distinct texture x multiplier)." % (
                sum(1 for r in textured if r[3]), len(factor)),
            "- Live textures: %d; missing or in no sheet (the three standalone PNGs aside): %d." % (
                len(live), len(missing)),
            "- Drawn PNGs nothing uses: %s." % (", ".join(unused) or "none"), ""]

    path = os.path.join(ROOT, DOC)
    with open(path, encoding="utf-8") as fh:
        head = fh.read().split(MARKER)[0]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(head + "\n".join(out))
    for line in missing:
        print("TEXTURES " + line)
    print("TEXTURES %d materials, %d recoloured by multiplier, %d live textures, %d problems"
          % (len(rows), sum(1 for r in textured if r[3]), len(live), len(missing)))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
